export const GET_ALL_MOVIES = "GET_ALL_MOVIES";

export const GET_ALL_SERIES = "GET_ALL_SERIES";

export const GET_ALL_GENRES = "GET_ALL_GENRES";

export const GET_REVIEWS_BY_MOVIES_ID = "GET_REVIEWS_BY_MOVIES_ID";
export const ADD_REVIEW = "ADD_REVIEW";
export const EDIT_REVIEW = "EDIT_REVIEW";